version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aegir
    versions:
    - 31.0.0
    - 31.0.1
    - 31.0.3
    - 31.0.4
    - 32.0.2
    - 32.1.0
    - 33.0.0
  - dependency-name: multihashes
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: multibase
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: err-code
    versions:
    - 3.0.0
  - dependency-name: ipfs-http-client
    versions:
    - 49.0.0
    - 49.0.1
  - dependency-name: ipfs
    versions:
    - 0.54.0
    - 0.54.1
